<?php
declare(strict_types=1);

namespace App\Tests;

use PHPUnit\Framework\TestCase;
use App\Stats\StatsService;
use App\Core\Database;

final class StatsServiceTest extends TestCase
{
    private StatsService $stats;
    private Database $db;

    protected function setUp(): void
    {
        $this->db = \App\Core\App::getInstance()->get(Database::class);
        $this->stats = new StatsService();
    }

    protected function tearDown(): void
    {
        $pdo = $this->db->getPdo();
        // Cleanup test data
        $pdo->exec("DELETE FROM tokens WHERE email LIKE '%@test.stats'");
        $pdo->exec("DELETE FROM submissions WHERE submitted_by LIKE '%@test.stats'");
        $pdo->exec("DELETE FROM forms WHERE slug LIKE 'test-stats-%'");
    }

    // ── getValidatorStats — invalidated_at filter ──────────────

    public function testGetValidatorStatsExcludesInvalidatedTokens(): void
    {
        $pdo = $this->db->getPdo();

        // Create test form + step
        $formId = \generate_uuid();
        $pdo->prepare("INSERT INTO forms (id, slug, label, description, actif, created_at) VALUES (?, 'test-stats-form', 'Test', '', 1, datetime('now'))")
            ->execute([$formId]);

        $stepId = \generate_uuid();
        $pdo->prepare("INSERT INTO steps (id, form_id, label, ordre, actif, `condition`) VALUES (?, ?, 'Step', 1, 1, '')")
            ->execute([$stepId, $formId]);

        // Create submission
        $subId = \generate_uuid();
        $pdo->prepare("INSERT INTO submissions (id, form_id, data, submitted_by, status, submitted_at) VALUES (?, ?, '{}', 'stats@test.stats', 'en_cours', datetime('now'))")
            ->execute([$subId, $formId]);

        // Create a DONE token (validated by user)
        $tokenId = \generate_uuid();
        $tokenVal = bin2hex(random_bytes(32));
        $pdo->prepare("INSERT INTO tokens (id, submission_id, step_id, email, token, sent_at, done_at, expires_at) VALUES (?, ?, ?, 'validator@test.stats', ?, datetime('now'), datetime('now'), datetime('now', '+7 days'))")
            ->execute([$tokenId, $subId, $stepId, $tokenVal]);

        // Create an INVALIDATED token (regenerated by admin)
        $invalidatedTokenId = \generate_uuid();
        $invalidatedTokenVal = bin2hex(random_bytes(32));
        $pdo->prepare("INSERT INTO tokens (id, submission_id, step_id, email, token, sent_at, done_at, invalidated_at, expires_at) VALUES (?, ?, ?, 'validator@test.stats', ?, datetime('now'), datetime('now'), datetime('now'), datetime('now', '+7 days'))")
            ->execute([$invalidatedTokenId, $subId, $stepId, $invalidatedTokenVal]);

        // getValidatorStats should count only the done token, not the invalidated one
        $stats = $this->stats->getValidatorStats();
        $validatorStats = null;
        foreach ($stats as $s) {
            if ($s['email'] === 'validator@test.stats') {
                $validatorStats = $s;
                break;
            }
        }

        self::assertNotNull($validatorStats, 'Validator stats should exist');
        self::assertSame(1, $validatorStats['done'], 'Only validated tokens should be counted as done');
        self::assertSame(0, $validatorStats['pending'], 'No pending tokens');
    }

    public function testGetValidatorStatsCountsPendingTokens(): void
    {
        $pdo = $this->db->getPdo();

        $formId = \generate_uuid();
        $pdo->prepare("INSERT INTO forms (id, slug, label, description, actif, created_at) VALUES (?, 'test-stats-pending', 'Test', '', 1, datetime('now'))")
            ->execute([$formId]);

        $stepId = \generate_uuid();
        $pdo->prepare("INSERT INTO steps (id, form_id, label, ordre, actif, `condition`) VALUES (?, ?, 'Step', 1, 1, '')")
            ->execute([$stepId, $formId]);

        $subId = \generate_uuid();
        $pdo->prepare("INSERT INTO submissions (id, form_id, data, submitted_by, status, submitted_at) VALUES (?, ?, '{}', 'stats-pending@test.stats', 'en_cours', datetime('now'))")
            ->execute([$subId, $formId]);

        // Create a pending token (no done_at)
        $tokenId = \generate_uuid();
        $tokenVal = bin2hex(random_bytes(32));
        $pdo->prepare("INSERT INTO tokens (id, submission_id, step_id, email, token, sent_at, expires_at) VALUES (?, ?, ?, 'validator-pending@test.stats', ?, datetime('now'), datetime('now', '+7 days'))")
            ->execute([$tokenId, $subId, $stepId, $tokenVal]);

        $stats = $this->stats->getValidatorStats();
        $validatorStats = null;
        foreach ($stats as $s) {
            if ($s['email'] === 'validator-pending@test.stats') {
                $validatorStats = $s;
                break;
            }
        }

        self::assertNotNull($validatorStats, 'Validator stats should exist');
        self::assertSame(0, $validatorStats['done'], 'No done tokens');
        self::assertSame(1, $validatorStats['pending'], 'One pending token');
    }
}
